ТЗ9/1
AlishevAzamat/java-filmorate pull request #2
Opened 2023-04-27 11:30 UTC by AlishevAzamat

Первая проверка

2023-04-28 08:43 UTC, TomattmanYandex requested changes
Привет, работа хорошая все комменты внутри. по поводу валидации
Если используешь текущий способ без аннотаций, то это не проблема, но лучше сделать в контроллере приватный метод который будет принимать обьект и валидировать его, если все норм ничего не делать а если есть проблемы, кидать ошибку, тогда при необходимости изменить валидацию, изменяешь только этот метод, и все работает дальше, сейчас же, чтобы изменить валидацию, необходимо будет во всех местах менять и не забывать

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Map<Integer, Film> films = new HashMap<>();
модификаторы доступа

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Название фильма пустое");
для этой проверки можно на поле в обьекте повесить аннотацию @NotEmpty

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > length) {
Для проверки длинны тоже есть стандартные аннотации

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDuration() < 0) {
и для такой проверки тоже

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film add(@RequestBody @Validated Film film) throws ValidationException {
кажется правильне использовать аннотацию - @Valid

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new ValidationException("Фильм не найден");
но это не ошибка валидации если что то не найдено, то это ошибка notFound

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
лучше бы добавить эту првоерку выше, так как после нее если она не прошла мы выходим из метода (зачем нам чуть что одно лишнее дейстиве
(Микро оптимизации))))

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.info("Фильм не найден");
Фильм?

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public ValidationException(String e) {
оштбку валидации кажется лучше унаследовать от RuntimeException все равно везде где мы ее используем она просто пробрасывается выше

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    int id;
модификатор доступа
и лучше использовать класс обертки вместо примитива
придёт к тебе объект с id 0 (вполне валидный id) как ты поймешь, это значение по умолчанию, или реальный id

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int duration;
тут тоже лучше обертку

2023-04-28 08:43 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id;
тут тоже лучше обертку

2023-04-28 08:43 UTC, TomattmanYandex commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void addFilms_errorChecking() throws ValidationException {
тестов мало, условий валидации множество, а тут проверяется только то что все корректно добавляется если нету ошибок, следует добавить по одному тесту на каждое валидируемое поле с проверкой что падает ошибка, один тест со всеми валидными полями
и точно так же для пользователя

2023-04-28 11:37 UTC, AlishevAzamat commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Название фильма пустое");
Достаточно повесить аннотация и все?
а проверка все равно должна быть в методе ? 
или же аннотация всю реализация возьмет на себя ?

2023-04-28 13:48 UTC, AlishevAzamat commented
ТЗ9/2

2023-04-29 15:05 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.info("Название фильма пустое");
когда мы на входной параметр контроллера повесим аннотацию @Valid то он пройдет валидацию по повешенным внутри параметрам

2023-04-29 15:07 UTC, TomattmanYandex approved these changes
Принято, мелкие исправления можно поправить к следующ0ему спринту

2023-04-29 15:07 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void check(Film film) {
лучше назвать метод validate а то не понятно что он чекает

2023-05-02 04:45 UTC, merged